version: "3.8"
services:
  db:
    container_name: postgres_workshop_db
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      app_network:
        aliases:
          - ${DB_HOST}

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
